language: node_js
node_js:
  - 'stable'
  #- '0.12'
  #- '0.10'
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm install codeclimate-test-reporter istanbul -g
script:
  - istanbul cover node_modules/mocha/bin/_mocha -- -R spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
